#!/bin/bash

INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc"
CONF_FILE="bashbreak.conf"

install() {
	echo "This will install bashbreak to $INSTALL_DIR. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ] ; then
		echo "Cancelled."
   		exit	
	else
		echo "Copying bashbreak to $INSTALL_DIR ..."
		cp ./bashbreak "$INSTALL_DIR" || exit 1
		echo "Copying default config file to $CONF_DIR/$CONF_FILE ..." 
		cp ./"$CONF_FILE" "$CONF_DIR" || exit 1 
	fi
	echo "Installation completed."
	echo "Type 'bashbreak -h' to see available commands."
	exit
}

uninstall() {
	echo "This will remove bashbreak and its config file. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ] ; then
		echo "Cancelled."
   		exit	
	else
		if [ -e "$INSTALL_DIR/bashbreak" ]; then
			rm -f "$INSTALL_DIR/bashbreak"
		fi
		if [ -e "$CONF_DIR/$CONF_FILE" ]; then
			rm -f "$CONF_DIR/$CONF_FILE"
		fi
	fi
	echo "Uninstallation completed."
	exit
	
}

case "$1" in

	"install")
		install;;

	"uninstall")
		uninstall;;

	*)
		echo 'Unknown command. Use "install" or "uninstall".';;
esac

exit
